### ISSUE TITLE
Imagem da pista esta errada

### ISSUE THREAD

**Issue by mbacefor** [BrunaDafne/DJlivery-jogo#2]
![image](https://github.com/BrunaDafne/DJlivery-jogo/assets/1368206/cf285782-02d7-475a-afc9-63515f3ea448)

A pista não aparecendo no lugar correto

**Comment by BrunaDafne** [comment]
Boa tarde, subi uma nova atualização e esse bug foi corrigido e está em produção!

Acesse pelo link: https://djlivery-jogo.vercel.app/

Qualquer dúvida ou problema pode reportar
